@baseUrl = http://localhost:3000/api/v1
@authToken = eyJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI2YWFlZGQyMGNmOGU2ZjY5MGI1M2Q4YTciLCJlbWFpbCI6InJvbmkuYmVuYW11QGdtYWlsLmNvbSIsImlzQnVzaW5lc3MiOnRydWUsImlzQWRtaW4iOnRydWUsImV4cCI6MTc4OTkwNzQ4NCwiaWF0IjoxNzg5OTAwMjg0fQ.MpAu4gk5Hk0eMRkI4xrO8ur4Mw_5T7FvjTL-muuE7FI
@cardId = 6aaede34cf8e6f690b53d8ac

### 1. Create New Card (Business / Admin Only)
POST {{baseUrl}}/cards
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "title": "yossef benamu",
  "subtitle": "full stack dev",
  "description": "portfolio",
  "web": "https://yossef-portfolio.netlify.app/",
  "address": {
    "street": "nez hehalav",
    "city": "modiin",
    "country": "israel",
    "state": "IL",
    "houseNumber": 3,
    "zip": "1234522"
  },
  "image": {
    "alt": "user-profile",
    "url": "https://yossef-portfolio.netlify.app/imege/WhatsApp%20Image%202026-02-06%20at%202.01.11%20PM.jpeg"
  },
  "phone": "0547898883",
  "email": "yossef.benamu@gmail.com"
}

### 2. Get All Cards (Public)
GET {{baseUrl}}/cards

### 3. Get My Cards (Logged-in User)
GET {{baseUrl}}/cards/my-cards
Authorization: Bearer {{authToken}}

### 4. Get Specific Card By ID (Public)
GET {{baseUrl}}/cards/{{cardId}}

### 5. Update Card (Owner / Admin Only)
PUT {{baseUrl}}/cards/{{cardId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "title": "yossef",
  "subtitle": "Full Stack Senior Developer",
  "description": "Updated web development portfolio and services",
  "web": "https://yossef-portfolio.netlify.app/",
  "address": {
    "street": "nez hehalav",
    "city": "modiin",
    "country": "israel",
    "state": "1",
    "houseNumber": 3,
    "zip": 1234522
  },
  "image": {
    "alt": "user-profile",
    "url": "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png"
  },
  "phone": "089755086",
  "email": "roni.benamu@gmail.com"
}

### 6. Toggle Like Status (Logged-in User)
PATCH {{baseUrl}}/cards/{{cardId}}
Authorization: Bearer {{authToken}}

### 7. Update Business Number (Admin Only)
PATCH {{baseUrl}}/cards/biz-number/{{cardId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "bizNumber": 9991112
}

### 8. Delete Card (Owner / Admin Only)
DELETE {{baseUrl}}/cards/{{cardId}}
Authorization: Bearer {{authToken}}