@baseUrl = http://localhost:3000/api/v1
@authToken = eyJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI2YWIyNDdmOGNmOGU2ZjY5MGI1M2Q4YjIiLCJlbWFpbCI6ImJlbmFtdUBnbWFpbC5jb20iLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiZXhwIjoxNzkwMDc1OTY5LCJpYXQiOjE3OTAwNjg3Njl9.R_szTzXGvmJvsTRC8srOuSsHyHkrmLMmRCfifXZR5Q8
@cardId = 6aaede34cf8e6f690b53d8ac

### 1. Create New Card (Business / Admin Only)
POST {{baseUrl}}/cards
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "title": "David benamu",
  "subtitle": "SVP - R&D and Generative AI manager",
  "description": "Citi grup",
  "web": "https://www.linkedin.com/in/david-benamu/",
  "address": {
    "street": "nez hehalav",
    "city": "modiin",
    "country": "israel",
    "state": "IL",
    "houseNumber": 3,
    "zip": "1234522"
  },
  "image": {
    "alt": "user-profile",
    "url": "https://media.licdn.com/dms/image/v2/C4D03AQF1_iD7CN94hQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1654257307296?e=1791417600&v=beta&t=_e6b1FcfxLZy2F9v5ZwNYA4LYStJuO-DToqOswMvXO4"
  },
  "phone": "0546746541",
  "email": "benamu@gmail.com"
}

### 2. Get All Cards (Public)
GET {{baseUrl}}/cards

### 3. Get My Cards (Logged-in User)
GET {{baseUrl}}/cards/my-cards
Authorization: Bearer {{authToken}}

### 4. Get Specific Card By ID (Public)
GET {{baseUrl}}/cards/{{cardId}}

### 5. Update Card (Owner / Admin Only)
PUT {{baseUrl}}/cards/{{cardId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "title": "yossef",
  "subtitle": "Full Stack Senior Developer",
  "description": "Updated web development portfolio and services",
  "web": "https://yossef-portfolio.netlify.app/",
  "address": {
    "street": "nez hehalav",
    "city": "modiin",
    "country": "israel",
    "state": "1",
    "houseNumber": 3,
    "zip": 1234522
  },
  "image": {
    "alt": "user-profile",
    "url": "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png"
  },
  "phone": "089755086",
  "email": "roni.benamu@gmail.com"
}

### 6. Toggle Like Status (Logged-in User)
PATCH {{baseUrl}}/cards/{{cardId}}
Authorization: Bearer {{authToken}}

### 7. Update Business Number (Admin Only)
PATCH {{baseUrl}}/cards/biz-number/{{cardId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "bizNumber": 9991112
}

### 8. Delete Card (Owner / Admin Only)
DELETE {{baseUrl}}/cards/{{cardId}}
Authorization: Bearer {{authToken}}