@baseUrl = http://localhost:3000/api/v1
@authToken = your Token
@cardId = your cardId

### 1. Create New Card (Business / Admin Only)
POST {{baseUrl}}/cards
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "title": "title",
  "subtitle": "subtitle",
  "description": "description",
  "web": " your url websit",
  "address": {
    "street": "your street",
    "city": "your city",
    "country": "your country",
    "state": "your state", 
    "houseNumber": "your houseNumber" , // is type: Number
    "zip": "your zip"
  },
  "image": {
    "alt": "your alt",
    "url": "your image url"
  },
  "phone": "your phone number",
  "email": "your email"
}

### 2. Get All Cards (Public)
GET {{baseUrl}}/cards

### 3. Get My Cards (Logged-in User)
GET {{baseUrl}}/cards/my-cards
Authorization: Bearer {{authToken}}

### 4. Get Specific Card By ID (Public)
GET {{baseUrl}}/cards/{{cardId}}

### 5. Update Card (Owner / Admin Only)
PUT {{baseUrl}}/cards/{{cardId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "title": "title",
  "subtitle": "subtitle",
  "description": "description",
  "web": "your url websit",
  "address": {
    "street": "your street",
    "city": "your city",
    "country": "your country",
    "state": "your state",
    "houseNumber": "your houseNumber" , // is type: Number
    "zip": "your zip"
  },
  "image": {
    "alt": "your alt",
    "url": "your image url"
  },
  "phone": "your phone number",
  "email": "your email"
}

### 6. Toggle Like Status (Logged-in User)
PATCH {{baseUrl}}/cards/{{cardId}}
Authorization: Bearer {{authToken}}

### 7. Update Business Number (Admin Only)
PATCH {{baseUrl}}/cards/biz-number/{{cardId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "bizNumber": 9991112
}

### 8. Delete Card (Owner / Admin Only)
DELETE {{baseUrl}}/cards/{{cardId}}
Authorization: Bearer {{authToken}}