@baseUrl = http://localhost:3000/api/v1
@authToken = your Token
@userId = your userId

### 1. Register / Create New User
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": {
    "first": "your first",
    "middleName": "your middleName",
    "last": "your last"
  },
  "address": {
    "street": "your street",
    "city": "your city",
    "country": "your country",
    "state": "your state",
    "houseNumber": "your houseNumber" , // is type: Number
    "zip": "your zip"
  },
  "image": {
    "alt": "your alt",
    "url": "your image url"
  },
  "phone": "your phone number",
  "email": "your email",
  "isBusiness": true,
  "password": "your password"
}

### 2. Login User
# @name login
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "your email",
  "password": "your password"
}

### 3. Get All Users (Admin Only)
GET {{baseUrl}}/users
Authorization: Bearer {{authToken}}

### 4. Get Specific User Profile
GET {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{authToken}}

### 5. Update User Profile (Full Payload)
PUT {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": {
    "first": "your first",
    "middleName": "your middleName",
    "last": "your last"
  },
  "address": {
    "street": "your street",
    "city": "your city",
    "country": "your country",
    "state": "your state",
    "houseNumber": "your houseNumber" , // is type: Number
    "zip": "your zip"
  },
  "image": {
    "alt": "your alt",
    "url": "your image url"
  },
  "phone": "your phone number"
}

### 6. Toggle Business Status (PATCH)
PATCH {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "isBusiness": true
}

### 7. Delete User Account
DELETE {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{authToken}}