@baseUrl = http://localhost:3000/api/v1
@authToken = eyJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI2YTcwNzU4ZTBmNWM1YjJiNzNmNTgxYTUiLCJlbWFpbCI6InJvbmkuYmVuYW11QGdtYWlsLmNvbSIsImlzQnVzaW5lc3MiOnRydWUsImlzQWRtaW4iOnRydWUsImV4cCI6MTc4OTg0NjIzMiwiaWF0IjoxNzg5ODM5MDMyfQ.9f-oT3UaWvRqorQoQjFNk-JhK4WkuXqeWFs8XKqZexg
@userId = 6a70758e0f5c5b2b73f581a5

### 1. Register / Create New User
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": {
    "first": "roni",
    "middleName": "",
    "last": "benamu"
  },
  "address": {
    "street": "נץ החלב",
    "city": "modiin",
    "country": "israel",
    "state": "10",
    "houseNumber": 10,
    "zip": "12345"
  },
  "image": {
    "alt": "user-profile",
    "url": "https://picsum.photos/200/300"
  },
  "phone": "0547898883",
  "email": "roni.benamu@gmail.com",
  "isBusiness": true,
  "password": "Roni-b707!"
}

### 2. Login User
# @name login
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "roni.benamu@gmail.com",
  "password": "Roni-b707!"
}

### 3. Get All Users (Admin Only)
GET {{baseUrl}}/users
Authorization: Bearer {{authToken}}

### 4. Get Specific User Profile
GET {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{authToken}}

### 5. Update User Profile (Full Payload)
PUT {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": {
    "first": "yossef",
    "middleName": "",
    "last": "benamu"
  },
  "address": {
    "street": "נץ החלב",
    "city": "modiin",
    "country": "israel",
    "state": "10",
    "houseNumber": 10,
    "zip": "12345"
  },
  "image": {
    "alt": "user-profile",
    "url": "https://picsum.photos/200/300"
  },
  "phone": "0547898883"
}

### 6. Toggle Business Status (PATCH)
PATCH {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "isBusiness": true
}

### 7. Delete User Account
DELETE {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{authToken}}